<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Title>World-Altering Editor MCP Server Library</Title>
    <Description>Model Context Protocol (MCP) Support Library for the World-Altering Editor</Description>
    <Copyright>Copyright © Rami 'Rampastring' Pasanen 2026</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\MapEditorLibrary\Version.cs" Link="Version.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="ModelContextProtocol" Version="2.1.0" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.3" />
    <PackageReference Include="Rampastring.XNAUI.WindowsDX" Version="4.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MapEditorLibrary\MapEditorLibrary.csproj" />
  </ItemGroup>

</Project>
