[TextShaping]
Enabled=true		; Shaping enabled. More performance intensive, but has letters laid out correctly
EnableBiDi=no		; Enable bidirectional text support (mixed LTR/RTL) for Arabic text
CacheSize=300		; Number of shaped text entries to cache. Higher values use more memory but improve performance

; Most text
[Font0]
Type=SystemFont
Family=Segoe UI
Style=Semibold
Size=12

; Headers
[Font1]
Type=SystemFont
Family=Segoe UI
Style=Bold
Size=13

[Font2]
Type=SpriteFont
Path=SpriteFont0.xnb

[Font3]
Type=SpriteFont
Path=SpriteFont1.xnb

[FontRendering]
KernelWidth=2
KernelHeight=2
FontResolutionFactor=2.5

; We have opted not to include Noto Sans in the repository due to its relatively large file size,
; and our sprite fonts already including CJK characters. If we did, it could be enabled by
; restoring the lines below.
;
;[FallbackFonts]
;Count=1
;Fallback0=NotoSansSC-Semibold.ttf
