<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Title>World-Altering Editor Library</Title>
    <Description>World-Altering Editor Core Library</Description>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FontStashSharp.MonoGame" Version="1.5.5" />
    <PackageReference Include="FontStashSharp.TextShapers.HarfBuzz" Version="1.2.3" />
    <PackageReference Include="HarfBuzzSharp" Version="8.3.1.2" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.3" />
    <PackageReference Include="Rampastring.Tools" Version="3.0.2" />
    <PackageReference Include="Rampastring.XNAUI.WindowsDX" Version="4.0.2" />
  </ItemGroup>

</Project>
